### ISSUE TITLE
Allow for metadata to be passed to the module.

### ISSUE THREAD

**Issue by phzietsman** [cloudandthings/terraform-aws-clickops-notifier#37]
Currently, when you get a notification it is not immediately clear for which account the event was (unless you've memorized all your account Ids).

This can be solved by passing in metadata that can be used to enrich the event for ease of use.

This data can easily be fetched from the organization, but we'd prefer not to give the ClickOps application more permissions than really needs.

A proposed structure: 
```yaml
clickops-metadata:
  accounts:
    123456789012:
      alias: "non-prod-app-a"
    123456789013:
      alias: "prod-app-b" 
```

Some checks:
- [ ] Basic validation to ensure keys are AWS account Ids
- [ ] Examples on how to dynamically get this from orgs and how to load from YAML
